- name: create user
  hosts: localhost
  tasks:
  - name: check the roboshop user exist or not
  #when you want to run the Linux command dirctly i.e, incase the ansible moudle is not avilable
  #when the user does not exist then ansible is treating it as error and comming out by default
  #ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output #output is variable name
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug:
      msg: "the output is {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop
    become: yes #we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0 #if this expression is true then only above module will run