- name: simple condition
  hosts: localhost
  vars: 
    NAME: DEVOPS
  tasks:
  - name: run this only if the name is DEVOPS
    ansible.builtin.debug:
      msg: "Hello, {{NAME}}"
    when: {{NAME}} == "DEVOPS"